### ISSUE TITLE
Any way to implement ?

### ISSUE THREAD

**Issue by dsmatana** [rtr-nettest/rmbtws#7]
Hello

I can't find any example of implementation.
Can you provide tutorial ?

Thanx

**Comment by helb** [comment]
Hi,
there's a pretty good example in [`test/Websockettest.html`](https://github.com/rtr-nettest/rmbtws/blob/5cac4e97c28438da49fb3c3318a499a1b6fbdaa0/test/Websockettest.html). 

If you have the RMBT backend server running somewhere, basically just:

- set your backend URL in [`Websockettest.html:8`](https://github.com/rtr-nettest/rmbtws/blob/5cac4e97c28438da49fb3c3318a499a1b6fbdaa0/test/Websockettest.html#L8)
- remove the hardcoded testserver override in [`Websockettest.js:25`](https://github.com/rtr-nettest/rmbtws/blob/5cac4e97c28438da49fb3c3318a499a1b6fbdaa0/src/Websockettest.js#L25)
- in your page, get user's `uuid` from `…/RMBTControlServer/settings` (POST request, store the uuid in cookie/localstorage/whatever), and use it instead of that hardcoded one in [`Websockettest.html:41`](https://github.com/rtr-nettest/rmbtws/blob/5cac4e97c28438da49fb3c3318a499a1b6fbdaa0/test/Websockettest.html#L41)
- enable logging if you want to (uncomment that block in [`Websockettest.html:45-49`](https://github.com/rtr-nettest/rmbtws/blob/5cac4e97c28438da49fb3c3318a499a1b6fbdaa0/test/Websockettest.html#L45-L49))
- run `gulp build` (or `gulp watch` to automatically rebuild when you chage files)
- start a webserver[*] in the cloned directory:

> Example webserver, using Python
> `$ python -m http.server 8000`  (or `-m SimpleHTTPServer 8000` for Python 2)

- point your browser to that server, eg. [`http://localhost:8000/test/Websockettest.html`](http://localhost:8001/test/Websockettest.html), open JS console (F12) to see the logs, click the *Start test* button
- use the supplied `TestVisualization.js` or create your own (i'm doing that just now)

---
 
[*] browsers have some security-related restrictions when acessing files from disk (using `file://` "protocol"), so running a local webserver usually works better

**Comment by cproof** [comment]
Hi,

Thanks for the interest, and thanks @helb for the explaination!

I tried updating the README and the `test/Websockettest.html` file for a better manual, also on how to use the `TestVisualization.js`

**Comment by dsmatana** [comment]
Thanks a lot !

**Comment by cifffi** [comment]
> in your page, get user's uuid from …/RMBTControlServer/settings (POST request, store the uuid in cookie/localstorage/whatever), and use it instead of that hardcoded one in Websockettest.html:41

Could you please explain a little more how to get user uuid? Thanks

**Comment by cproof** [comment]
Hi,

you have to send a `POST` request to your ControlServer to `/settings` with some base settings, e.g.

`POST https: //c01.example.at/RMBTControlServer/settings`
```json
{
          "version_name": "0.1",
          "language": "de",
          "type": "DESKTOP",
          "version_code": "1",
          "name": "RMBT",
          "terms_and_conditions_accepted": "true",
          "terms_and_conditions_accepted_version": 5
      }
```

In the response, you can find (among other settings from the `settings` table and the ControlServer `Configuration.properties` the client `uuid` issued by the ControlServer.

A sample response looks like e.g.

```json
{
    "settings": [{
        "urls": {
            "url_share": "https://example.at/share/",
            "url_ipv6_check": "https://c01v6.example.at/RMBTControlServer/ip",
            "control_ipv4_only": "c01v4.example.at",
            "open_data_prefix": "https://www.example.at/de/Opentest?",
            "url_map_server": "https://map.example.at/RMBTMapServer",
            "url_ipv4_check": "https://c01v4.example.at/RMBTControlServer/ip",
            "control_ipv6_only": "c01v6.example.at",
            "statistics": "https://www.example.at/de/Statistik#noMMenu"
        },
        "qostesttype_desc": [{
            "name": "Webseite",
            "test_type": "WEBSITE"
        }, {
            "name": "Unveränderter Inhalt",
            "test_type": "HTTP_PROXY"
        }, {
            "name": "Transparente Verbindung",
            "test_type": "NON_TRANSPARENT_PROXY"
        }, {
            "name": "DNS",
            "test_type": "DNS"
        }, {
            "name": "TCP Ports",
            "test_type": "TCP"
        }, {
            "name": "UDP Ports",
            "test_type": "UDP"
        }, {
            "name": "Voice over IP",
            "test_type": "VOIP"
        }, {
            "name": "Traceroute",
            "test_type": "TRACEROUTE"
        }, {
            "name": "Traceroute",
            "test_type": "TRACEROUTE_MASKED"
        }],
        "versions": {
            "control_server_version": "open-rmbt_init-706-g3ce481865"
        },
        "history": {
            "devices": [],
            "networks": []
        },
        "uuid": "27705927-0b4e-4521-ae3f-86f29e02ac4d",
        "map_server": {
            "port": 443,
            "host": "map.example.at",
            "ssl": true
        }
    }],
    "error": []
}
```

**Comment by cifffi** [comment]
Hi,
I've implemented .../RMBTControlServer/settings call and now I'm getting issued uuid, but the very next call seems to be broken, even if the return code is 200.
It is a POST .../RMBTControlServer/testRequest with request body
`{
    "version": "0.3",
    "language": "de",
    "uuid": "eb91b4e2-1247-43fb-89b7-5b5a0fd61d64",
    "type": "DESKTOP",
    "version_code": "0.3",
    "client": "RMBTws",
    "timezone": "Europe/Vienna",
    "time": 1564470328475
}`

and response
`{
    "error": ["Could not generate a response to your request."],
    "error_flags": [{}]
}`

The last thing I see in logs is "test scheduled for start in undefined second(s)", because the response is not in valid format I guess and whole test is stuck on INIT phase.

Could you help me with what is wrong?
Thank you

**Comment by cproof** [comment]
Do you have any error log on your ControlServer `catalina.out`?

**Comment by cifffi** [comment]
> New settings request from *MY_IP*
Settings request from *MY_IP* completed (12 ms)
30-Jul-2019 09:29:41.384 INFO [http-nio-8080-exec-7] org.restlet.engine.log.LogFilter.afterHandle 2019-07-30    09:29:41        *MY_IP*    -       10.0.11.213     8080    POST    /RMBTControlServer/settings     -       200     1105$
30-Jul-2019 09:29:41.415 INFO [http-nio-8080-exec-4] org.restlet.engine.log.LogFilter.afterHandle 2019-07-30    09:29:41        *MY_IP*    -       10.0.11.213     8080    GET     /RMBTControlServer/requestDataCollector -       200 $
New test request from *MY_IP*
Error generating Answer org.json.JSONException: could not find server
Could not generate a response to your request.
Test request from *MY_IP* completed (60 ms)
{"error":["Could not generate a response to your request."],"error_flags":[{}]}
30-Jul-2019 09:29:41.493 INFO [http-nio-8080-exec-8] org.restlet.engine.log.LogFilter.afterHandle 2019-07-30    09:29:41        *MY_IP*    -       10.0.11.213     8080    POST    /RMBTControlServer/testRequest  -       200     79  $

**Comment by cproof** [comment]
This error is thrown as the ControlServer is not able to lookup any suitable test server. You'll need a server of `server_type` `RMBThttp` in your `test_server` table that can be returned to the client.

I'll update the `rmbt_init.sql` accordingly over the next days so that such a entry is also provided in the example. But for now, you can simply copy the demo server and change its `server_type` (along with the `uuid` of course)

**Comment by cifffi** [comment]
Thanks, I've got a little further, but there is another issue I'm facing...
I've updated test_server instance again and set web_address_ipv4 to 'IP:8080', because that is where my test server is running. Right now when I start test I see:

> error occurred during websocket test: WebSocket initialization failed
> rmbtws.js:306 wss://IP:8080:443

Where does this 443 port come from?

**Comment by cproof** [comment]
The test_server-table contains fields `port` and `port_ssl`, please use these instead of `web_address_ipv4`.

**Comment by cifffi** [comment]
I've just tried that, values from web, and port are ignored, it still took value of web_address_ipv4, even if it is null (wss://:443) .. I updated pors_ssl and set it to NULL, and now it looks like this wss://:0)
So I guess I need to keep value in web_address_ipv4 and put 8080 to port_ssl even if it's not entirely correct.

EDIT: doesn't work either .. test_server_encryption is set to true therefore wss:// is being accessed instead of ws:// 
Is it because port_ssl is filled?

**Comment by cproof** [comment]
As encryption is mandatory for RMBTws clients, `port_ssl` is always used (as well as "wss"). Using this without encryption will cause problems with certain network elements.
In case you want to disable encryption anyway, you need to change the ControlServer code (https://github.com/rtr-nettest/open-rmbt/blob/master/RMBTControlServer/src/at/rtr/rmbt/controlServer/RegistrationResource.java#L280)
